language: python
python:
  - '3.6'
install:
  - pip install nose twine
script:
  - ./setup.py build sdist
  - twine check dist/*
  - pip install .
  - nosetests
deploy:
  provider: pypi
  user: pfariello
  password:
    secure: gtUvvQrBz0/9aWrGqaRT1MQ8nD+0hkC9qCyqPHgR4y9dbHJU2h3sTmaF7hbSiB1q5zk8BghNFpYkPQMOQK36ei6kxdFdrv2xY5sTjpVkXVZw7dSnu7xwTuQMW1qjsdPpzqez08l3u4w4uDUgh/Dibqoeboo5U7FXJUaf44/2xtzKD3Q6zo9yT1T8TmdCIwAdOlSxmCP4dhzRckHoGCyJhHeP+h3iYZUVsGCI/IfV9IxnKWbhKIhRDBpSH0L87vuk1cDvbYfs59rCGQuMg3WqVyFjYapXykqhbpdtGOuGC0jVSa/kjl+5wS118LxQ0A0VW+nmSsRMQOSv6anRJ4XKVQRdGhEHKh939lwUkC80woEeS3mr/HTmjzvhRTm0W0FOqSpBMJYtEJCy2e7jocZBMH8zyrM84z70Ez4kwdrqmq+3qJMD4UsF6vSIa9jdgvfWl09raNoMEdQH1tlA+KQgcf+LU5CshyfpjWrFkg02I5iYJo+YZUPEX2yujeXbb5Wv42+QhU6bTjyK28QlioR77xGtT/hCGPIZnhZhBaM8HN2eFBQdr9f8gz50NfjOsXI9X5ThDhtdKQ9TF1c0y9um1R84etVFLYa1vWvXBXw3QuEWHmhIFuZ+uzPvdS7zIdlmTArZxqkIbaWO8+8L6aoSoFHu8kkS3zljVwvEG0IUV1w=
  on:
    tags: true
    python: '3.6'
  skip_existing: true
